"use client";

import { SiteFooter } from "@/components/recovery/site-footer";
import { SiteHeader } from "@/components/recovery/site-header";
import { useLanguage } from "@/components/recovery/language-provider";

export default function PrivacyPage() {
  const { t } = useLanguage();
  return (
    <main className="inner-page">
      <SiteHeader />
      <article className="legal-shell">
        <h1>{t("Privacy policy", "سیاست حریم خصوصی")}</h1>
        <p>{t("Last updated September 24, 2026", "آخرین به‌روزرسانی: ۲۴ سپتامبر ۲۰۲۶")}</p>
        <div className="legal-card dashboard-card">
          <section><h2>{t("Privacy is part of the product", "حریم خصوصی بخشی از محصول است")}</h2><p>{t("Recovery Inventory lets you create an anonymous account with a private alias, username, password, and recovery code, or choose verified email access. A real name and email are not required for anonymous membership. Inventory content is encrypted before storage.", "Recovery Inventory به شما اجازه می‌دهد یک حساب ناشناس با نام مستعار، نام کاربری، رمز عبور و کد بازیابی خصوصی بسازید، یا ورود با ایمیل تأییدشده را انتخاب کنید. برای عضویت ناشناس نام واقعی و ایمیل لازم نیست. محتوای ترازنامه پیش از ذخیره شدن رمزگذاری می‌شود.")}</p></section>
          <section><h2>{t("Information we process", "اطلاعاتی که پردازش می‌کنیم")}</h2><ul><li>{t("Your alias or display name, your chosen username, and your email address only if you choose email access or add it later.", "نام مستعار یا نام نمایشی، نام کاربری انتخابی و فقط در صورت انتخاب ورود ایمیلی یا افزودن آن در آینده، آدرس ایمیل شما.")}</li><li>{t("One-way password and recovery-code hashes, plus short-lived hashed email verification codes when email access is used. Passwords and recovery codes are not stored in readable form.", "هش یک‌طرفه رمز عبور و کد بازیابی، و هنگام استفاده از ورود ایمیلی، کدهای تأیید هش‌شده و کوتاه‌مدت. رمزهای عبور و کدهای بازیابی به شکل خوانا ذخیره نمی‌شوند.")}</li><li>{t("Encrypted Step 4 and Step 10 entries, dates, and basic account settings.", "مطالب رمزگذاری‌شده گام ۴ و گام ۱۰، تاریخ‌ها و تنظیمات پایه حساب.")}</li><li>{t("Subscription status and Stripe customer identifiers—not full card details.", "وضعیت عضویت و شناسه‌های مشتری Stripe — نه اطلاعات کامل کارت.")}</li><li>{t("Limited technical and security logs provided by our hosting service.", "گزارش‌های فنی و امنیتی محدود که توسط سرویس میزبانی ارائه می‌شود.")}</li></ul></section>
          <section><h2>{t("Payments", "پرداخت‌ها")}</h2><p>{t("Stripe processes payments and may request an email address, billing address, or other information required to complete a transaction. Stripe handles that information under its own privacy policy. Recovery Inventory does not receive your full card number.", "Stripe پرداخت‌ها را پردازش می‌کند و ممکن است ایمیل، آدرس صورتحساب یا اطلاعات دیگری را که برای تکمیل تراکنش لازم است درخواست کند. Stripe این اطلاعات را مطابق سیاست حریم خصوصی خود مدیریت می‌کند. Recovery Inventory شماره کامل کارت شما را دریافت نمی‌کند.")}</p></section>
          <section><h2>{t("How information is used", "نحوه استفاده از اطلاعات")}</h2><p>{t("We use information only to operate the journal, protect accounts, send requested sign-in or verification messages, provide support, process memberships, and comply with law. We do not sell inventory content or use it for advertising.", "ما اطلاعات را فقط برای اجرای دفتر، محافظت از حساب‌ها، ارسال پیام‌های درخواستی ورود یا تأیید، ارائه پشتیبانی، پردازش عضویت و رعایت قانون استفاده می‌کنیم. محتوای ترازنامه را نمی‌فروشیم و برای تبلیغات استفاده نمی‌کنیم.")}</p></section>
          <section><h2>{t("Privacy-safe site analytics", "آمار وب‌سایت با حفظ حریم خصوصی")}</h2><p>{t("To understand which public pages, languages, and broad referral categories are useful, we keep daily aggregate counts of public page views and selected account milestones, such as opening the demo or membership page, creating an account, starting checkout, or activating a membership. We do not use analytics cookies, visitor IDs, IP addresses, precise locations, full referring URLs, search terms, or advertising pixels. Analytics does not record inventory content, notes, inventory dates, recovery codes, account or payment identifiers, or how members use the private inventory tools. Global Privacy Control and Do Not Track requests are respected. Aggregate website analytics are kept for up to 13 months.", "برای اینکه بدانیم کدام صفحه‌های عمومی، زبان‌ها و دسته‌های کلی ارجاع مفید هستند، مجموع روزانه بازدید صفحه‌های عمومی و چند مرحله انتخابی حساب مانند باز کردن نمونه یا صفحه عضویت، ساخت حساب، آغاز پرداخت یا فعال کردن عضویت را نگهداری می‌کنیم. از کوکی آماری، شناسه بازدیدکننده، نشانی IP، مکان دقیق، نشانی کامل ارجاع، عبارت جست‌وجو یا پیکسل تبلیغاتی استفاده نمی‌کنیم. آمار وب‌سایت محتوای ترازنامه، یادداشت‌ها، تاریخ ترازنامه، کدهای بازیابی، شناسه حساب یا پرداخت و نحوه استفاده اعضا از ابزارهای خصوصی ترازنامه را ثبت نمی‌کند. درخواست‌های Global Privacy Control و Do Not Track رعایت می‌شوند. مجموع آمار وب‌سایت حداکثر ۱۳ ماه نگهداری می‌شود.")}</p></section>
          <section><h2>{t("Your choices", "انتخاب‌های شما")}</h2><p>{t("You may stay anonymous with username-and-password access and a separately saved recovery code, or add verified email access to the same account later. Adding either login method does not move or copy inventory; it keeps the same account and progress. You decide whether to share, print, or export an inventory.", "می‌توانید با ورود نام کاربری و رمز عبور و یک کد بازیابی جداگانه ذخیره‌شده ناشناس بمانید، یا بعداً ورود با ایمیل تأییدشده را به همان حساب اضافه کنید. افزودن هر روش ورود، ترازنامه را منتقل یا کپی نمی‌کند و همان حساب و پیشرفت را نگه می‌دارد. شما تصمیم می‌گیرید ترازنامه را به اشتراک بگذارید، چاپ یا صادر کنید.")}</p></section>
          <section><h2>{t("Security and limits", "امنیت و محدودیت‌ها")}</h2><p>{t("We use encryption in transit, encrypted inventory storage, salted password hashing, hashed recovery and verification codes, restricted session cookies, short code expiration, and attempt limits. No online service can promise absolute security. Anonymous members must copy or download their recovery code and keep it private as independent backup access.", "ما از رمزگذاری هنگام انتقال، ذخیره‌سازی رمزگذاری‌شده ترازنامه، هش امن رمز عبور با نمک، کدهای بازیابی و تأیید هش‌شده، کوکی‌های نشست محدود، زمان انقضای کوتاه کد و محدودیت تلاش استفاده می‌کنیم. هیچ سرویس آنلاین نمی‌تواند امنیت مطلق را تضمین کند. اعضای ناشناس باید کد بازیابی خود را کپی یا دانلود کرده و به‌عنوان دسترسی پشتیبان مستقل خصوصی نگه دارند.")}</p></section>
          <section><h2>{t("Contact", "تماس")}</h2><p>{t("Privacy questions: support@recoveryinventory.com", "پرسش‌های مربوط به حریم خصوصی: support@recoveryinventory.com")}</p></section>
        </div>
      </article>
      <SiteFooter />
    </main>
  );
}
